from __future__ import annotations

from app.agents.base import AgentContext
from app.agents.craft_chat import detect_domain, format_rows, run_craft_qa
from app.core.config import get_settings
from app.models.schemas import ChatRequest
from app.services.paper_urls import resolve_paper_url


def _session_context(ctx: AgentContext) -> str:
    hyps = ctx.session.state.hypotheses
    lines = [f"Research query: {ctx.query}"]
    if hyps:
        lines.append("Active hypotheses:")
        for i, h in enumerate(hyps[:5], 1):
            lines.append(f"  {i}. {h.statement} (confidence {h.confidence}%)")
    concept_count = sum(1 for n in ctx.session.state.graph.nodes if n.type == "concept")
    paper_count = len(ctx.session.papers)
    lines.append(f"Corpus: {paper_count} papers, {concept_count} concepts in graph.")
    return "\n".join(lines)


async def answer(ctx: AgentContext, req: ChatRequest) -> dict:
    message = req.message
    focus_label = None
    if req.focusNodeId:
        node = next(
            (n for n in ctx.session.state.graph.nodes if n.id == req.focusNodeId), None
        )
        if node:
            focus_label = node.label

    hits = ctx.vectors.search(ctx.corpus_id, message, k=8)
    citations: list[dict] = []
    seen: set[str] = set()
    context_blocks: list[str] = []

    for hit in hits:
        meta = hit["meta"]
        pid = meta.get("paper_id")
        if not pid or pid in seen:
            continue
        seen.add(pid)
        rec = ctx.session.papers.get(pid)
        title = meta.get("title", rec.title if rec else pid)
        source = meta.get("source", rec.source if rec else "derived")
        url = resolve_paper_url(rec) if rec else None
        if not url:
            node = next((n for n in ctx.session.state.graph.nodes if n.id == pid), None)
            url = node.url if node else None
        citations.append({
            "paperId": pid,
            "title": title,
            "source": source,
            "url": url,
        })
        url_note = f" ({url})" if url else ""
        context_blocks.append(f"[{title}]{url_note}\n{hit['document'][:400]}")

    await ctx.audit(
        "chat", "Retrieve evidence",
        detail=f"{len(citations)} sources · gemini={'on' if ctx.llm.enabled else 'off'}",
        params={"k": len(citations), "focus": req.focusNodeId, "message": message[:80]},
    )

    # CRAFT text-to-SQL routing: if the question maps to one of the CRAFT /
    # Spider-2.0 databases, answer it from real records via generate_sql +
    # execute_query rather than (or in addition to) the literature corpus.
    settings = get_settings()
    domain = detect_domain(message, settings)
    craft_qa = await run_craft_qa(ctx, message, domain) if domain else None
    craft_block = ""
    if craft_qa:
        craft_block = (
            f"CRAFT DATABASE ({craft_qa['label']} · {craft_qa['connection']}"
            f" · {'live' if craft_qa['live'] else 'demo'}) — real records, not literature.\n"
            f"Generated SQL:\n{craft_qa['sql']}\n\n"
            f"Result rows:\n{format_rows(craft_qa['rows'], craft_qa['columns'])}"
        )
        citations.append({
            "paperId": f"craft:{craft_qa['domain']}",
            "title": f"CRAFT · {craft_qa['label']} ({craft_qa['connection']})",
            "source": craft_qa["source"],
            "url": None,
        })

    session_ctx = _session_context(ctx)
    corpus_block = "\n\n".join(context_blocks) if context_blocks else "(No closely matching papers in corpus.)"

    content = None
    if ctx.llm.enabled:
        focus_line = f"\nUser is focused on graph node: {focus_label}" if focus_label else ""
        craft_section = f"\n\nCRAFT DATA QUERY (authoritative — quote the numbers):\n{craft_block}" if craft_block else ""
        craft_instr = (
            "\n6. A CRAFT data query ran against a real database — lead with those exact "
            "numbers, then explain what they mean and show the SQL was auto-generated by "
            "CRAFT's semantic layer."
            if craft_block else ""
        )
        prompt = f"""You are SynthesisOS, an expert research assistant. You answer biomedical questions from literature, and you also investigate real datasets through CRAFT's text-to-SQL semantic layer.

{session_ctx}{focus_line}

INGESTED LITERATURE (prioritize when relevant — cite paper titles):
{corpus_block}{craft_section}

USER QUESTION:
{message}

Instructions:
1. Answer clearly in 3–8 sentences (longer if the question is complex).
2. When the question relates to the session corpus, ground your answer in the ingested literature and mention paper titles.
3. If the question is outside the corpus scope, still answer helpfully using established scientific knowledge — prefix that portion with "General context:" so the user knows it is not from their uploaded/fetched papers.
4. If both corpus and general knowledge apply, combine them and distinguish sources.
5. Be direct; do not refuse reasonable out-of-scope questions.{craft_instr}"""
        content = ctx.llm.complete_interactive(prompt)

    if not content and ctx.llm.quota_exhausted:
        corpus_hint = ""
        if context_blocks:
            snippet = context_blocks[0].split("\n", 1)[-1][:220]
            corpus_hint = f"Based on your corpus ({len(citations)} sources): {snippet}…"
        content = (
            "Gemini rate limit reached (free tier ≈5 requests/min). "
            "Wait about a minute and try again, or set GEMINI_USE_IN_PIPELINE=false in backend/.env "
            "so the research pipeline does not consume your quota. "
            + (corpus_hint or "Try a simpler question or browse the graph and hypotheses meanwhile.")
        )

    if not content:
        if craft_qa:
            headline = _craft_headline(craft_qa)
            content = (
                f"CRAFT queried the {craft_qa['label']} database "
                f"({'live' if craft_qa['live'] else 'demo'}) with auto-generated SQL. {headline}"
            )
        elif context_blocks:
            lead = context_blocks[0].split("\n", 1)[-1][:280]
            content = (
                f"From {len(citations)} papers in your corpus: {lead} "
                "Open the cited papers below for full context."
            )
        else:
            content = (
                "I couldn't find closely matching papers in this session's corpus. "
                "Try rephrasing, uploading a relevant PDF, or broadening your initial research query. "
                "Add a GOOGLE_API_KEY to enable Gemini for general biomedical Q&A beyond the corpus."
            )

    content = content.strip()
    # Always surface the underlying data + SQL so the answer is auditable.
    if craft_block:
        content = f"{content}\n\n```sql\n{craft_qa['sql']}\n```\n{format_rows(craft_qa['rows'], craft_qa['columns'])}"

    return {"content": content, "citations": citations}


def _craft_headline(craft_qa: dict) -> str:
    """One-line natural summary of the top CRAFT result row (Gemini-free fallback)."""
    rows = craft_qa.get("rows") or []
    if not rows:
        return "The query returned no rows for these filters."
    top = rows[0]
    cols = list(top.keys())
    label = str(top.get(cols[0]))
    if len(cols) > 1:
        metric = cols[1]
        return f"Top result: {label} with {top.get(metric):,} {metric.replace('_', ' ')}." if isinstance(top.get(metric), int) else f"Top result: {label} ({metric} = {top.get(metric)})."
    return f"Top result: {label}."
